FROM python:3.8-slim

# 设置工作目录
WORKDIR /app

# 复制项目文件
COPY ../src/server /app/
COPY ../depreciation_model.h5 /app/
COPY ../scaler.pkl /app/
COPY ../encoder.pkl /app/
COPY ../src/server/requirements.txt /app/

# 安装依赖
RUN pip install --no-cache-dir -r requirements.txt

# 监听的默认端口
EXPOSE 5000
# 运行 Flask 应用
CMD ["python", "app.py"]
